# Generated by Django 2.2.19 on 2021-04-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(verbose_name='Active'),
        ),
    ]
